version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=false
      - HOST=0.0.0.0
      - PORT=8000
    volumes:
      # Optional: Mount data directory if you want to update data without rebuilding
      - ./backend/data:/app/data:ro
    restart: unless-stopped

  # Optional: Frontend service for development
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/
    profiles:
      - dev
